name: py
on:
  schedule:
    - cron: "40 * * * *" // once an hour

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: run linux.pu # run the run.py to get the latest data
        run: |
          python linux.py
