name: Compile for Linux

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10 #install the python needed
          run: |
      - name: install pip
        run: |
            python -m pip install --upgrade pip
      - name: install webcolors
        run: |
            pip install webcolors
      - name: execute script # run file
        run: |
          python linux.py

            
